version: '2'

services:
  php-app:
    build: .
    volumes:
      - ./html:/var/www/html

  nginx-proxy:
    image: nginx
    links:
      - php-app
    volumes:
      - ./html:/var/www/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"